// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-N0kcdqfCME22O3TiZpZ5UKWZLJjn40',
    appId: '1:146555961059:web:36665cfe72b5c4e938cfd6',
    messagingSenderId: '146555961059',
    projectId: 'picpoint-7b4fa',
    authDomain: 'picpoint-7b4fa.firebaseapp.com',
    storageBucket: 'picpoint-7b4fa.firebasestorage.app',
    measurementId: 'G-JD05FX9MJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4JfEGhwtB6rdrf-3nbgd9YT7EvTYItg',
    appId: '1:146555961059:android:ff57a7b80b9e9f5238cfd6',
    messagingSenderId: '146555961059',
    projectId: 'picpoint-7b4fa',
    storageBucket: 'picpoint-7b4fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHsyBPf7hWaCORBDpjgDbBk8vQtzRMHVE',
    appId: '1:146555961059:ios:a58eb3664a45e75738cfd6',
    messagingSenderId: '146555961059',
    projectId: 'picpoint-7b4fa',
    storageBucket: 'picpoint-7b4fa.firebasestorage.app',
    iosBundleId: 'com.example.picPoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHsyBPf7hWaCORBDpjgDbBk8vQtzRMHVE',
    appId: '1:146555961059:ios:a58eb3664a45e75738cfd6',
    messagingSenderId: '146555961059',
    projectId: 'picpoint-7b4fa',
    storageBucket: 'picpoint-7b4fa.firebasestorage.app',
    iosBundleId: 'com.example.picPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-N0kcdqfCME22O3TiZpZ5UKWZLJjn40',
    appId: '1:146555961059:web:499df523e365a75f38cfd6',
    messagingSenderId: '146555961059',
    projectId: 'picpoint-7b4fa',
    authDomain: 'picpoint-7b4fa.firebaseapp.com',
    storageBucket: 'picpoint-7b4fa.firebasestorage.app',
    measurementId: 'G-WJP932FR9X',
  );
}
